server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: enrollment
          uri: http://localhost:8081
          predicates:
            - Path=/enrollments/** 
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path= /meetingroomlists/**
        - id: management
          uri: http://localhost:8083
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: enrollment
          uri: http://enrollment:8080
          predicates:
            - Path=/enrollments/** 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path= /meetingroomlists/**
        - id: management
          uri: http://management:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
